In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [ ]:
# General Logic on if-else,Looping,OOPS (Basic) & Functions
class Student:

  def calculate_avg(self):
    avg = 0
    for i in range(len(self.marks)):
      avg+=self.marks[i]
    avg/=len(self.marks)
    return avg

  def assign_grade(self):
    if(self.avg>=90):
      return "A"
    elif (self.avg>=75):
      return "B"
    elif(self.avg>=60):
      return "C"
    else:
      return "D"

  def has_failed(self):
    for i in range(len(self.marks)):
      if(self.marks[i]<40):
        return True
    else:
      return False

  def display_details(self):
    print("Name:{}".format(self.name))
    print("Marks:{}".format(self.marks))
    print("Avg:{}".format(self.avg))
    print("Has Failed:{}".format(self.has_failed()))
    print("Grade:{}".format(self.grade))

  def __init__(self,roll,marks,name):
    self.name = name
    self.roll = roll
    self.marks = marks
    self.avg = self.calculate_avg()
    self.grade = self.assign_grade()

In [ ]:
## More Logic on Functions & Tuples

# (candidate_name, constituency, votes)

def analyze_election(data):
  total_votes = 0
  highest_votes = 0
  for i in range(len(data)):
    total_votes+=data[i][2]
    if(highest_votes<=data[i][2]):
      highest_votes = i
  print("Total Votes: {}".format(total_votes))
  print("Candidate with Highest Votes: {} winning with {} votes".format(data[highest_votes][0],data[highest_votes][2]))
  print("Constituency:{}".format(data[highest_votes][1]))
  if(data[highest_votes][2]>=0.5*total_votes):
    has_50 = True
    print("{} secured More than 50% of Votes".format(data[highest_votes][0]))
  return (data[highest_votes][0], data[highest_votes][2], total_votes,data[highest_votes][1],has_50)




In [ ]:
# Usage of Modules, importing coupled with logic and OOPS
%%writefile geometry.py
import math

class Rectangle:

    def __init__(self, length, width):
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width

    def perimeter(self):
        return 2 * (self.length + self.width)

    def diagonal(self):
        return math.sqrt(self.length**2 + self.width**2)

    def is_square(self):
        if self.length == self.width:
            return True
        else:
            return False



Writing geometry.py


In [ ]:
from geometry import Rectangle
import math
import random
r1 = Rectangle(10, 5)
r2 = Rectangle(6, 6)

print("Rectangle 1 Area:", r1.area())
print("Rectangle 1 Perimeter:", r1.perimeter())
print("Rectangle 1 Diagonal:", r1.diagonal())

if r1.is_square():
    print("Rectangle 1 is a square")
else:
    print("Rectangle 1 is not a square")

print(random.randint(5,1000))

print("Rectangle 2 Area:", r2.area())

if r2.is_square():
    print("Rectangle 2 is a square")
else:
    print("Rectangle 2 is not a square")

Rectangle 1 Area: 50
Rectangle 1 Perimeter: 30
Rectangle 1 Diagonal: 11.180339887498949
Rectangle 1 is not a square
857
Rectangle 2 Area: 36
Rectangle 2 is a square


In [ ]:
## Testing on Functions(multiple Returns), Args and kwargs, Built in Attributes
def analyze_numbers(*args, operation="all", **kwargs):
  absolute = kwargs.get("absolute", False)
  round_to = kwargs.get("round_to", None)

  def summation(*args,**kwargs):
    summer = 0
    for i in range(len(args)):
      summer = summer + args[i]
    if(kwargs["absolute"]==True):
      summer = abs(summer)
    if(kwargs["round_to_int"]):
      summer = round(summer,kwargs["round_to_int"])
    return summer

  def avg(*args):
    sum = summation(*args)
    return sum/len(args)
  def minmax(*args):
    mini = 0
    maxi = 0
    if(kwargs["absolute"]==True):
      mini = abs(min(*args))
      maxi = abs(max(*args))
    if(kwargs["round_to_int"]):
      mini = round(min(*args),kwargs["round_to_int"])
      maxi = round(max(*args),kwargs["round_to_int"])
    return mini,maxi
  def all(*args):
    return summation(args),avg(args),minmax(args)

  if(operation=="all"):
    return all(*args)
  elif(operation=="avg"):
    return avg(*args)
  elif(operation=="minmax"):
    return minmax(*args)
  elif(operation=="summation"):
    return summation(*args)
  else:
    return None



In [ ]:
def analyze_numbers(*args, operation="all", **kwargs):
    absolute = kwargs.get("absolute", False)
    round_to = kwargs.get("round_to", None)

    numbers = []

    for value in args:
        if isinstance(value, (int, float)):
            if absolute:
                value = abs(value)
            numbers.append(value)

    if len(numbers) == 0:
        return None

    total = 0
    minimum = numbers[0]
    maximum = numbers[0]

    for num in numbers:
        total += num
        if num < minimum:
            minimum = num
        if num > maximum:
            maximum = num

    average = total / len(numbers)

    if round_to is not None:
        total = round(total, round_to)
        average = round(average, round_to)
        minimum = round(minimum, round_to)
        maximum = round(maximum, round_to)

    if operation == "sum":
        return total
    elif operation == "avg":
        return average
    elif operation == "minmax":
        return (minimum, maximum)
    elif operation == "all":
        return (total, average, minimum, maximum)
    else:
        return None


In [ ]:
# Testing on Generators, Iterators, Lists and Sets
def analyze_collections(lst):
  lt = []
  st = {}
  # Unique Elements and Multiple Appearing Elements
  for i in range(len(lst)):
    if(lt.count(lst[i])==0):
      lt.append(lst[i])
    else:
      st.add(lst[i])
  # Generator
  def gen(lst):
    for i in range(len(lst)):
      if(lst[i]%3==0):
        yield lst[i]

  return lt,st,gen(lst)




In [ ]:
# Testing on Lists and Sets
# Remove duplicates

# Preserve original order

# Remove negative numbers

# Return:

# cleaned list

# set of removed elements
def clean_data(lst):
    cleaned = []
    removed = set()
    seen = set()
    for item in lst:
        if item < 0:
            removed.add(item)
        elif item not in seen:
            seen.add(item)
            cleaned.append(item)
        else:
            removed.add(item)
    return cleaned, removed




In [ ]:
# OOPS Higher Practice
class Student:
  def __init__(self,name):
    self.name = name
    self._marks = 0
    self.__grade = "F"
  def set_marks(self,mks):
    self._marks = mks
    self.__calculate_grade()
  def __calculate_grade(self):
    if(self._marks>=90):
      self.__grade = "A"
    elif(self._marks>=80):
      self.__grade = "B"
    elif(self._marks>=70):
      self.__grade = "C"
    else:
      self.__grade = "D"
  def get_grade(self):
    return self.__grade

In [3]:
# Practice on Dictionaries Logic
marks = {
    "Alice":[85,90,78],
    "Bob":[70,88,82],
    "Charlie":[95,92,93],
    "David":[60,65,58]
}


def assign_avg_grade(lt):
  avg = 0
  grade=""
  avg = sum(lt)/len(lt)
  if(avg>=90):
    grade = "A"
  elif(avg>=80):
    grade="B"
  elif(avg>=70):
    grade="C"
  else:
    grade="D"
  return avg,grade

result={}
for x in marks:
  v1,v2= assign_avg_grade(marks[x])
  result[x]={"avg":v1,"grade":v2}



## Numpy


In [7]:
import numpy as np
arr = np.array([[1,2],[2,3],[3,4]],dtype=int)
print(arr)
print(type(arr))

[[1 2]
 [2 3]
 [3 4]]
<class 'numpy.ndarray'>


In [15]:
arr = np.random.randn(4,5)
arr

array([[ 1.76678778,  1.28078086,  1.27979525, -1.10185996,  0.93517012],
       [ 0.23284912, -0.01936989, -0.47035583,  1.045835  ,  0.76709695],
       [-1.92904915,  0.30158354,  0.15444984, -0.35461729,  0.44559939],
       [ 1.5795191 , -1.18624767, -0.86305344, -1.46830557,  0.60376324]])

In [21]:
x = np.arange(5,12,2).reshape(4,1)
x

array([[ 5],
       [ 7],
       [ 9],
       [11]])

In [26]:
x = np.ones((2,3),dtype=int)
y = np.zeros((4,6),dtype=float)
print(x)
y

[[1 1 1]
 [1 1 1]]


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
# For Identity Matrix
arr = np.identity(7)
arr

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [40]:
# For Random Numbers
x = np.random.randint(1,100,size=(2,3))
y = np.random.randn(3,4)
z = np.linspace(1,100,10).reshape(2,5)
print(z.ndim,z)
print(len(z))

2 [[  1.  12.  23.  34.  45.]
 [ 56.  67.  78.  89. 100.]]
2


In [44]:
# Attributes of Numpy
a2 = np.arange(8).reshape(2,2,2)
print(a2.ndim)
print(a2.size)
print(len(a2))
print(a2.shape)
# Changing Dtype
a2.astype(np.int32)
print(a2)

3
8
2
(2, 2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [49]:
# Array Operations
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
print(a1*3)
print(a1+3)
print(a1/3)
print(np.dot(a1,a2))
a3 = a1 @ a2
print(a3)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[0.         0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.         2.33333333]
 [2.66666667 3.         3.33333333 3.66666667]]
[[114 120 126]
 [378 400 422]
 [642 680 718]]
[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [62]:
# Array Functions
import numpy as np

data = np.array([
    [30, 45, 60, 75, 90],
    [15, 25, 35, 45, 55],
    [60, 70, 80, 90, 100],
    [10, 20, 30, 40, 50],
    [85, 88, 92, 95, 98],
    [5, 15, 25, 35, 45]
])

# Max - Min of the Dataset
print(np.max(data))
print(np.min(data))


# Mean of each device
mean_data = np.mean(data,axis=1)

# Std of Time interval
time_std = np.std(data,axis=1)
# Converting from degrees to Radians
rad = data * np.pi / 180
res = np.sin(rad) + np.cos(rad)



100
5


In [66]:
import numpy as np

data = np.array([
    [30, 45, 60, 75, 90],
    [15, 25, 35, 45, 55],
    [60, 70, 80, 90, 100],
    [10, 20, 30, 40, 50],
    [85, 88, 92, 95, 98],
    [5, 15, 25, 35, 45]
])

# Log
L = np.log(1 + data)

# Advanced Normalization
col_mean = np.mean(data, axis=0)
col_std = np.std(data, axis=0)

Z = (data - col_mean) / col_std
Z

array([[-0.14332591,  0.04312697,  0.24735893,  0.48076197,  0.72708908],
       [-0.6592992 , -0.6961925 , -0.7290579 , -0.7554831 , -0.76985903],
       [ 0.88862066,  0.96727631,  1.0284924 ,  1.09888451,  1.15478855],
       [-0.83129029, -0.88102237, -0.92434127, -0.96152395, -0.98370876],
       [ 1.74857613,  1.63266383,  1.49717248,  1.30492536,  1.06924865],
       [-1.00328139, -1.06585224, -1.11962463, -1.16756479, -1.19755849]])

In [68]:
data = np.array([
    [30, 45, 60, 75, 90],
    [15, 25, 35, 45, 55],
    [60, 70, 80, 90, 100],
    [10, 20, 30, 40, 50],
    [85, 88, 92, 95, 98],
    [5, 15, 25, 35, 45]
])

max_row = np.max(data,axis=1)
min_col = np.min(data,axis=0)
print(max_row)
print(min_col)

[ 90  55 100  50  98  45]
[ 5 15 25 35 45]


In [74]:
# Using Mathematical Functions
def sigmoid(arr):
  return 1 / (1 + np.exp((-arr)))
a = np.arange(10).reshape(5,2)
print(sigmoid(a))

def ReLU(arr):
  return np.where(arr>=0,arr,0)
print(ReLU(a))

[[0.5        0.73105858]
 [0.88079708 0.95257413]
 [0.98201379 0.99330715]
 [0.99752738 0.99908895]
 [0.99966465 0.99987661]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## Indexing, Slicing and Fancy Indexing

In [38]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1[:],a2[:,2:3])

[0 1 2 3 4 5 6 7 8 9] [[ 2]
 [ 6]
 [10]]


In [39]:
a3[:,:,0:1]

array([[[0],
        [2]],

       [[4],
        [6]]])

In [40]:
a = np.arange(24).reshape(6,4)
a[0::2]
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [41]:
arr = np.random.randint(1,100,24).reshape(6,4)
arr[[0,2,4]]


array([[93, 53, 73, 89],
       [51, 14, 87, 96],
       [88, 53, 87, 41]])

In [42]:
arr = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(arr)
print(b)
print(arr+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [43]:
# Working with Missing Values
arr = np.array([1,2,3,4,5,np.nan,6])
arr[~np.isnan(arr)]

array([1., 2., 3., 4., 5., 6.])

In [44]:
import numpy as np

A = np.arange(1, 26).reshape(5, 5)
print(A[[0,2,4]])
print(A[[0,1,2,4],[0,2,4,1]])

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
[ 1  8 15 22]


In [45]:
print(A[(A%3==0) & (A>10)])
print(A[[0,0,-1,-1],[0,-1,0,-1]])

[12 15 18 21 24]
[ 1  5 21 25]


In [46]:
# Argmax & Argmin --> Gives indices
print(A)
print(np.argmin(A,axis=0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[0 0 0 0 0]


In [48]:
# Where function --> np.where(condition,true,false)
print(arr)
np.where(arr>2,0,arr)

[ 1.  2.  3.  4.  5. nan  6.]


array([ 1.,  2.,  0.,  0.,  0., nan,  0.])

In [58]:
# Sorting & Append & Delete
A = np.linspace(15,5,10)
print(A)
# np.sort(A)
B = np.random.randn(4,3)
B = np.append(B,np.ones(B.shape[1]))
B

[15.         13.88888889 12.77777778 11.66666667 10.55555556  9.44444444
  8.33333333  7.22222222  6.11111111  5.        ]


array([ 0.58705864,  1.69282356,  2.04897155,  0.04457685,  1.84211436,
       -0.10055727, -0.45244351,  2.11798334, -0.19290471,  0.64858036,
       -0.30081115, -0.27790775,  1.        ,  1.        ,  1.        ])

In [3]:
import numpy as np
arr = np.array([[[1,2],[2,3]],[[3,4],[4,5]]])

arr

array([[[1, 2],
        [2, 3]],

       [[3, 4],
        [4, 5]]])

In [12]:
arr[[0,1],[0,1],:]

array([[1, 2],
       [4, 5]])